### ISSUE TITLE
Which IP cores u are using? Could u tell me the names?

### ISSUE THREAD

**Issue by fdchenwenhan** [MasLiang/CNN-On-FPGA#1]
Which IP cores u are using?  Could u tell me the names? I cann't find those missing modules.

**Comment by MasLiang** [comment]
Sorry to that. 
I complemented the whole project. It can help you.

**Comment by MasLiang** [comment]
sorry, i will complement the whole project.
Just wait.

**Comment by MasLiang** [comment]
I added a new .txt file, it may help you

**Comment by fdchenwenhan** [comment]
I get it now! Thank you very much!

-----原始邮件-----
发件人:MasLiang ***@***.***>
发送时间:2021-04-02 16:06:56 (星期五)
收件人: MasLiang/CNN-On-FPGA ***@***.***>
抄送: fdchenwenhan ***@***.***>, Author ***@***.***>
主题: Re: [MasLiang/CNN-On-FPGA] Which IP cores u are using? Could u tell me the names? (#1)



I added a new .txt file, it may help you

**Comment by fdchenwenhan** [comment]
> I added a new .txt file, it may help you
I got it ! Thank you very much！
